# 指定应用名称
spring:
  application:
    name: eureka-server

# 指定端口号
server:
  port: 7011



# spring cloud 配置
eureka:
  # 暴露当前eureka服务的注册地址
  client:
    service-url:
      defaultZone: http://127.0.0.1:7011/eureka/,http://127.0.0.1:7021/eureka/

    # 指定不向eureka注册
    register-with-eureka: false

    # 启动时不尝试向eureka注册
    fetch-registry: false

  instance:
    hostname: localhost


  server:
    # 关闭eureka自我保护机制
    enable-self-preservation: false
    # 指定eureka client失败自动剔除服务 检测时间
    eviction-interval-timer-in-ms: 10000

